

//------------------------------------------------------------------------------------------------------

/*

     Generated by GX Zeus Advanced data exporting script v1.03 (by geloxo)

     Usage: Save this content to a sqf file and run that file during your mission.
            You can also import that .sqf into GX Zeus again for further editing.
            To import scripts place them in: \userconfig\gx_zeus\gx_zeus_script.sqf

*/

if (not(isServer)) exitWith {};

gx_curator_load = [];
gx_curator_loadversion = 1.03;
_sleeptime = 0.001;


// ********* Zeus CURRENT SELECTION from user: Sgt Angel ************* 



//Exported objects: 0



//Exported vehicles: 0



//Exported groups: 0



publicVariable 'gx_curator_load';
publicVariable 'gx_curator_loadversion';

if (true) exitWith {};

/*

     Exported Objects:  2
     Exported Vehicles: 0
     Exported Groups:   0
     Exported Units:    0

     Total Input Items: 2
     Missed Items:      0

     End of exporting

*/

//------------------------------------------------------------------------------------------------------

